name: SonarCloud Analysis

on:
  push:
    branches:
      - develop  # Hoặc nhánh mà bạn muốn kiểm tra (ví dụ: 'develop')
  pull_request:
    branches:
      - develop  # Hoặc nhánh bạn muốn kiểm tra (ví dụ: 'develop')

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}  # Lưu token trong GitHub Secrets